
## Señal de reloj.
set_property PACKAGE_PIN W5 [get_ports clk]
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

## Interruptores
#set_property PACKAGE_PIN V17 [get_ports {digitos[0]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {digitos[0]}]
#set_property PACKAGE_PIN V16 [get_ports {digitos[1]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {digitos[1]}]
#set_property PACKAGE_PIN W16 [get_ports {digitos[2]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {digitos[2]}]
#set_property PACKAGE_PIN W17 [get_ports {digitos[3]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {digitos[3]}]
#set_property PACKAGE_PIN W15 [get_ports {digitos[4]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {digitos[4]}]
#set_property PACKAGE_PIN V15 [get_ports {digitos[5]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {digitos[5]}]
#set_property PACKAGE_PIN W14 [get_ports {digitos[6]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {digitos[6]}]
#set_property PACKAGE_PIN W13 [get_ports {digitos[7]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {digitos[7]}]
#set_property PACKAGE_PIN V2 [get_ports {digitos[8]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {digitos[8]}]
#set_property PACKAGE_PIN T3 [get_ports {digitos[9]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {digitos[9]}]
#set_property PACKAGE_PIN T2 [get_ports {digitos[10]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {digitos[10]}]
#set_property PACKAGE_PIN R3 [get_ports {digitos[11]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {digitos[11]}]
#set_property PACKAGE_PIN W2 [get_ports {digitos[12]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {digitos[12]}]
#set_property PACKAGE_PIN U1 [get_ports {digitos[13]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {digitos[13]}]
#set_property PACKAGE_PIN T1 [get_ports {digitos[14]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {digitos[14]}]
#set_property PACKAGE_PIN R2 [get_ports {digitos[15]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {digitos[15]}]


## LEDs
set_property PACKAGE_PIN U16 [get_ports {bin_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bin_data[0]}]
set_property PACKAGE_PIN E19 [get_ports {bin_data[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {bin_data[1]}]
set_property PACKAGE_PIN U19 [get_ports {bin_data[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {bin_data[2]}]
set_property PACKAGE_PIN V19 [get_ports {bin_data[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {bin_data[3]}]
set_property PACKAGE_PIN W18 [get_ports {bin_data[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {bin_data[4]}]
set_property PACKAGE_PIN U15 [get_ports {bin_data[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {bin_data[5]}]
set_property PACKAGE_PIN U14 [get_ports {bin_data[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {bin_data[6]}]
set_property PACKAGE_PIN V14 [get_ports {bin_data[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {bin_data[7]}]
set_property PACKAGE_PIN V13 [get_ports {bin_data[8]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {bin_data[8]}]
set_property PACKAGE_PIN V3 [get_ports {bin_data[9]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {bin_data[9]}]
set_property PACKAGE_PIN W3 [get_ports {bin_data[10]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {bin_data[10]}]
set_property PACKAGE_PIN U3 [get_ports {bin_data[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {bin_data[11]}]
#set_property PACKAGE_PIN P3 [get_ports {led[12]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
#set_property PACKAGE_PIN N3 [get_ports {led[13]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
#set_property PACKAGE_PIN P1 [get_ports {led[14]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
#set_property PACKAGE_PIN L1 [get_ports {led[15]}]
#	set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]


## Led de 7 segmentos
## drivers de transistor PNP de anodo
set_property PACKAGE_PIN U2 [get_ports {display[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {display[0]}]
set_property PACKAGE_PIN U4 [get_ports {display[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {display[1]}]
set_property PACKAGE_PIN V4 [get_ports {display[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {display[2]}]
set_property PACKAGE_PIN W4 [get_ports {display[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {display[3]}]

## Leds de 7 segmentos
## segmentos
set_property PACKAGE_PIN W7 [get_ports {segmentos[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {segmentos[0]}]
set_property PACKAGE_PIN W6 [get_ports {segmentos[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segmentos[1]}]
set_property PACKAGE_PIN U8 [get_ports {segmentos[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {segmentos[2]}]
set_property PACKAGE_PIN V8 [get_ports {segmentos[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {segmentos[3]}]
set_property PACKAGE_PIN U5 [get_ports {segmentos[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {segmentos[4]}]
set_property PACKAGE_PIN V5 [get_ports {segmentos[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {segmentos[5]}]
set_property PACKAGE_PIN U7 [get_ports {segmentos[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {segmentos[6]}]

## punto decimal
set_property PACKAGE_PIN V7 [get_ports {segmentos[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {segmentos[7]}]


## Botones
set_property PACKAGE_PIN U18 [get_ports reset]
	set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN T18 [get_ports button]
        set_property IOSTANDARD LVCMOS33 [get_ports button]


set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
